### ISSUE TITLE
How can I change a font of text in a chart, if I can at all?

### ISSUE THREAD

**Issue by D1fify** [g-battaglia/kerykeion#128]

**Comment by g-battaglia** [comment]
Hi, the chart is just a SVG, so if you want to change it's font family you can add to the SVG file basic CSS, like that:

```css
svg {
    font-family: "Roboto", sans-serif;
}
```
